services:
    db:
        image: "mysql:${MYSQL_VERSION}" # amd64 and arm64
        command: mysqld --default-authentication-plugin=mysql_native_password --expire_logs_days=3
        cap_add:
          - SYS_NICE  # CAP_SYS_NICE, fix error mbind: Operation not permitted
        restart: unless-stopped
        ports:
            - "${MYSQL_HOST_PORT}:3306"
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./mysql/data:/var/lib/mysql
    fuseki:
        image: "secoresearch/fuseki:${GRAPHDB_VERSION}"
        restart: unless-stopped
        volumes:
        # Persistent volume mounts
        - './fuseki/config/log4j2.properties:/jena-fuseki/log4j2.properties' # override config 
        # Docker volume mounts
        - fuseki-data:/fuseki-base/databases
        user: root  # Run the container with root user
        ports:
        - "${GRAPHDB_HOST_PORT}:3030"
        environment:
        - JVM_ARGS=-Xmx4G -Dlog4j2.formatMsgNoLookups=true # CVE-2021-44228 [MIT2021]
        - ADMIN_PASSWORD=${GRAPHDB_ADMIN_PASSWORD}
        - ENABLE_DATA_WRITE=true
        - ENABLE_UPDATE=true
        - ENABLE_UPLOAD=true
        - QUERY_TIMEOUT=60000 # in milliseconds (60 seconds by default)


    mediawiki:
        image: "opensemanticlab/osl-mw:${MW_VERSION}"
        restart: unless-stopped
        depends_on:
            - db
            - elasticsearch
            - memcached
            - fuseki
            - drawio
        ports:
            - "${MW_HOST_PORT}:80"
        volumes:
            # Persistent volume mounts
            - ./mediawiki/config/CustomSettings.php:/var/www/html/w/CustomSettings.php
            # Docker volume mounts
            - mediawiki:/mediawiki # solve unnamed volume issue
            - mediawiki-data:/var/www/html/w/images
        environment:
            - TZ=${MW_TIME_ZONE}
            - MW_SITE_SERVER=${MW_SITE_SERVER}
            - MW_SITE_NAME=${MW_SITE_NAME}
            - MW_SITE_LANG=${MW_SITE_LANG}
            - MW_TIME_ZONE=${MW_TIME_ZONE}
            - MW_DEFAULT_SKIN=Citizen
            - MW_ENABLE_UPLOADS=1
            - MW_USE_INSTANT_COMMONS=0
            - MW_ADMIN_USER=admin
            - MW_ADMIN_PASS=${MW_ADMIN_PASS}
            - MW_DB_NAME=mediawiki
            - MW_DB_USER=mwuser
            - MW_DB_PASS=${MW_DB_PASS}
            - MW_DB_INSTALLDB_USER=root
            - MW_DB_INSTALLDB_PASS=${MYSQL_ROOT_PASSWORD}
            - MW_AUTOUPDATE=true
            - MW_REINSTALL=true
            - MW_AUTOINSTALL_CA_CERTS=false
            - MW_PAGE_PACKAGES=${MW_PAGE_PACKAGES}
            - MW_AUTOIMPORT_PAGES=${MW_AUTOIMPORT_PAGES}
            - MW_AUTOBUILD_SITEMAP=${MW_AUTOBUILD_SITEMAP}
            - MW_MAIN_CACHE_TYPE=CACHE_MEMCACHED
            - MW_MEMCACHED_SERVERS=memcached:11211
            - MW_SEARCH_TYPE=CirrusSearch
            - MW_CIRRUS_SEARCH_SERVERS=elasticsearch
            - MW_REST_DOMAIN=mediawiki
            - MW_FLOW_NAMESPACES=NS_TALK,NS_USER_TALK
            - PHP_LOG_ERRORS=On
            - PHP_ERROR_REPORTING=E_ALL #Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
            - DRAWIO_SERVER=${DRAWIO_SERVER} #public url

    memcached:
        image: "memcached:${MEMCACHED_VERSION}"
        restart: unless-stopped

    elasticsearch:
        # image: arm64v8/elasticsearch:8.18.0
        image: "elasticsearch:${ELASTICSEARCH_VERSION}" # amd64 and arm64
        # platform: linux/arm64
        restart: unless-stopped
        environment:
           - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
           - "discovery.type=single-node"

    drawio:
        image: jgraph/drawio:${DRAWIO_VERSION}
        restart: unless-stopped
        ports:
            - "${DRAWIO_HOST_PORT}:8080"

volumes:
    mediawiki: {}
    mediawiki-data: {}
    fuseki-data: {}
