# create mount points if not existing
#   mkdir -p mysql/data
#   mkdir -p mediawiki/data && chown www-data:www-data mediawiki/data
#   mkdir -p blazegraph/data

version: '3.8'
services:
    db:
        image: mysql:8.0.17
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - "${MYSQL_HOST_PORT}:3306"
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./mysql/data:/var/lib/mysql

    graphdb:
        image: nawer/blazegraph
        restart: unless-stopped
        environment:
            JAVA_XMS: 512m
            JAVA_XMX: 1g
        volumes:
            - ./blazegraph/data:/var/lib/blazegraph
            - ./blazegraph/config:/docker-entrypoint-initdb.d
        ports:
            - "${GRAPHDB_HOST_PORT}:9999"

    mediawiki:
        image: opensemanticlab/osl-mw:main
        restart: unless-stopped
        depends_on:
            - db
            - elasticsearch
            - memcached
            - graphdb
            - drawio
        ports:
            - "${MW_HOST_PORT}:80"
        volumes:
            - ./mediawiki/config/CustomSettings.php:/var/www/html/w/CustomSettings.php
            - ./mediawiki/data:/var/www/html/w/images
        environment:
            - TZ=${MW_TIME_ZONE}
            - MW_SITE_SERVER=${MW_SITE_SERVER}
            - MW_SITE_NAME=${MW_SITE_NAME}
            - MW_SITE_LANG=${MW_SITE_LANG}
            - MW_TIME_ZONE=${MW_TIME_ZONE}
            - MW_DEFAULT_SKIN=timeless
            - MW_ENABLE_UPLOADS=1
            - MW_USE_INSTANT_COMMONS=0
            - MW_ADMIN_USER=admin
            - MW_ADMIN_PASS=${MW_ADMIN_PASS}
            - MW_DB_NAME=mediawiki
            - MW_DB_USER=mwuser
            - MW_DB_PASS=${MW_DB_PASS}
            - MW_DB_INSTALLDB_USER=root
            - MW_DB_INSTALLDB_PASS=${MYSQL_ROOT_PASSWORD}
            - MW_AUTOUPDATE=true
            - MW_REINSTALL=true
            - MW_AUTOINSTALL_CA_CERTS=false
            - MW_PAGE_PACKAGES=${MW_PAGE_PACKAGES}
            - MW_AUTOIMPORT_PAGES=${MW_AUTOIMPORT_PAGES}
            - MW_MAIN_CACHE_TYPE=CACHE_MEMCACHED
            - MW_MEMCACHED_SERVERS=memcached:11211
            - MW_SEARCH_TYPE=CirrusSearch
            - MW_CIRRUS_SEARCH_SERVERS=elasticsearch
            - MW_REST_DOMAIN=mediawiki
            - MW_FLOW_NAMESPACES=NS_TALK,NS_USER_TALK
            - PHP_LOG_ERRORS=On
            - PHP_ERROR_REPORTING=E_ALL #Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
            - DRAWIO_SERVER=${DRAWIO_SERVER} #public url

    memcached:
        image: memcached
        restart: unless-stopped

    elasticsearch:
        image: elasticsearch:6.5.4
        restart: unless-stopped
        environment:
           - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
           - "discovery.type=single-node"

    drawio:
        image: jgraph/drawio
        restart: unless-stopped
        ports:
            - "${DRAWIO_HOST_PORT}:8080"

